### ISSUE TITLE
LET NEPTUNE STRIKE YE DEAD WINSLOW

### ISSUE THREAD

**Issue by goolord** [chessai/1password-beta-nix#1]
HAAAAARK! HARK, TRITON! HARK!
BELLOW, BID OUR FATHER, THE SEA KING, RISE FROM THE DEPTHS, FULL FOUL
IN HIS FURY, BLACK WAVES TEEMING WITH SALT-FOAM, TO SMOTHER
THIS YOUNG MOUTH WITH PUNGENT SLIME…
… TO CHOKE YE, ENGORGING YOUR ORGANS TILL YE TURN BLUE AND
BLOATED WITH BILGE AND BRINE AND CAN SCREAM NO MORE…
ONLY WHEN HE, CROWNED IN COCKLE SHELLS WITH
SLITHERING TENTACLED TAIL AND STEAMING BEARD,
TAKE UP HIS FELL, BE-FINNÈD ARM — HIS CORAL-TINED TRIDENT
SCREECHES BANSHEE-LIKE IN THE TEMPEST AND PLUNGES RIGHT THROUGH YER GULLET,
BURSTING YE, A BULGING BLADDER NO MORE,
BUT A BLASTED BLOODY FILM NOW — A NOTHING
FOR THE HARPIES AND THE SOULS OF DEAD SAILORS TO PECK AND CLAW AND FEED
UPON ONLY TO BE LAPPED UP AND SWALLOWED BY THE INFINITE WATERS OF
THE DREAD EMPEROR HIMSELF…
FORGOTTEN TO ANY MAN, TO ANY TIME, FORGOTTEN TO ANY GOD OR DEVIL,
FORGOTTEN EVEN TO THE SEA… FOR ANY STUFF OR PART OF WINSLOW, EVEN
ANY SCANTLING OF YOUR SOUL, IS WINSLOW NO MORE, BUT IS NOW ITSELF
THE SEA.

**Comment by chessai** [comment]
got too many urkels on your team, that's why your winslow

**Comment by goolord** [comment]
i'm eminem
